"""add_duration_to_plays

Revision ID: a177b40308fa
Revises: afc02555f961
Create Date: 2025-03-29 18:47:54.560813+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a177b40308fa'
down_revision: Union[str, None] = 'afc02555f961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plays', 'duration')
    # ### end Alembic commands ###
