"""add_duration_to_plays

Revision ID: 7ce6c3784371
Revises: a177b40308fa
Create Date: 2025-03-29 19:00:12.081325+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce6c3784371'
down_revision: Union[str, None] = 'a177b40308fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('duration', sa.Integer(), nullable=True, comment='Duration in seconds'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plays', 'duration')
    # ### end Alembic commands ###
